embed_size = 512
embed_proj_size = 512
max_seq_length = 512
hidden_size = 512
dropout_rate = 0.2
num_layers = 2
is_bidirectional = False
data_path = 'dataset/cleaned_train_length.csv'
train_path = 'dataset/fold_3/train.csv'
val_path = 'dataset/fold_3/validation.csv'
batch_size = 8  # Set your desired batch size
num_epochs = 5
lr = 1e-3
cross_val = 4
logfile = 'logs/logfile4.log'
checkpoint_path = f'model_checkpoint_{4}.pth'
checkpoint_target_model = 'model_checkpoint_3.pth'
num_classes = 7
LABEL2IDX = {}
IDX2LABEL = {idx:label for label,idx in LABEL2IDX.items()}